//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Patient
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        [Display(Name = "Name")]
        [Required(ErrorMessage ="Please enter you name")]
        [DataType(DataType.Text, ErrorMessage ="Please enter a valid name")]
        public string NAME { get; set; }
        [Required(ErrorMessage ="Please enter an age")]
        [Display(Name = "Age")]
        public int AGE { get; set; }
        [Required(ErrorMessage ="Address Field is Required")]
        [RegularExpression("^([A-PR-UWYZ0-9][A-HK-Y0-9][AEHMNPRTVXY0-9]?[ABEHMNPRVWXY0-9]? {1,2}[0-9][ABD-HJLN-UW-Z]{2}|GIR 0AA)$", ErrorMessage ="Invalid Address. Note: must be upper case")]
        [Display(Name = "Your address")]
        public string ADDRESS { get; set; }
        [Display(Name = "Gender")]
        public string GENDER { get; set; }
        [Display(Name = "Registered at clinic")]
        public Nullable<int> REGISTERED_AT_CLINIC { get; set; }

        public virtual Clinic Clinic { get; set; }
        public virtual Gender Gender1 { get; set; }
    }
}
